export const reviews = [
  {
    id: 1,
    productId: 1,
    name: "Rahul Sharma",
    rating: 5,
    review: "Amazing sound quality and very comfortable to wear.",
  },
  {
    id: 2,
    productId: 1,
    name: "Priya Verma",
    rating: 4,
    review: "Good headphones for the price. Battery life is impressive.",
  },
  {
    id: 3,
    productId: 1,
    name: "Aman Singh",
    rating: 5,
    review: "Really liked the bass and overall sound quality.",
  },
  {
    id: 4,
    productId: 1,
    name: "Neha Gupta",
    rating: 4,
    review: "Comfortable even after using them for a few hours.",
  },
  {
    id: 5,
    productId: 1,
    name: "Rohan Mehta",
    rating: 3,
    review: "Sound is good, but the build quality could be better.",
  },
  {
    id: 6,
    productId: 1,
    name: "Sneha Patel",
    rating: 5,
    review: "Battery easily lasts me the whole day. Very satisfied.",
  },
  {
    id: 7,
    productId: 1,
    name: "Arjun Kumar",
    rating: 4,
    review: "Bluetooth connects quickly and the range is pretty good.",
  },
  {
    id: 8,
    productId: 1,
    name: "Ananya Roy",
    rating: 5,
    review: "Great for music and online classes. Definitely worth buying.",
  },
  {
    id: 9,
    productId: 1,
    name: "Vikas Yadav",
    rating: 3,
    review: "Decent headphones, but the ear cushions get warm after long use.",
  },
  {
    id: 10,
    productId: 1,
    name: "Karan Malhotra",
    rating: 4,
    review: "Good sound, nice design and solid battery backup.",
  },
];

export const items = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 2499,
    image: "https://placehold.co/300x300?text=Headphones",
    disc: "Comfortable wireless headphones with clear sound and long battery life.",
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 3999,
    image: "https://placehold.co/300x300?text=Smart+Watch",
    disc: "Stylish smartwatch with fitness tracking and notification support.",
  },
  {
    id: 3,
    name: "Gaming Mouse",
    price: 1299,
    image: "https://placehold.co/300x300?text=Gaming+Mouse",
    disc: "Ergonomic gaming mouse with adjustable DPI and responsive controls.",
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    price: 3499,
    image: "https://placehold.co/300x300?text=Keyboard",
    disc: "Mechanical keyboard with tactile switches and backlit keys.",
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    price: 1999,
    image: "https://placehold.co/300x300?text=Speaker",
    disc: "Portable Bluetooth speaker with powerful sound and compact design.",
  },
  {
    id: 6,
    name: "Laptop Stand",
    price: 999,
    image: "https://placehold.co/300x300?text=Laptop+Stand",
    disc: "Adjustable laptop stand designed for comfortable desk setups.",
  },
  {
    id: 7,
    name: "Power Bank",
    price: 1499,
    image: "https://placehold.co/300x300?text=Power+Bank",
    disc: "10000mAh portable power bank with fast charging support.",
  },
  {
    id: 8,
    name: "USB-C Hub",
    price: 1799,
    image: "https://placehold.co/300x300?text=USB-C+Hub",
    disc: "Multi-port USB-C hub for connecting multiple devices.",
  },
  {
    id: 9,
    name: "Webcam",
    price: 2299,
    image: "https://placehold.co/300x300?text=Webcam",
    disc: "Full HD webcam suitable for video calls, meetings and streaming.",
  },
  {
    id: 10,
    name: "Desk Lamp",
    price: 899,
    image: "https://placehold.co/300x300?text=Desk+Lamp",
    disc: "Minimal LED desk lamp with adjustable brightness.",
  },
];
