export const reviews = [
  {
    id: 1,
    productId: 1,
    name: "Rahul Sharma",
    rating: 5,
    review: "Amazing sound quality and very comfortable to wear.",
  },
  {
    id: 2,
    productId: 1,
    name: "Priya Verma",
    rating: 4,
    review: "Good headphones for the price. Battery life is impressive.",
  },
  {
    id: 3,
    productId: 1,
    name: "Aman Singh",
    rating: 5,
    review: "Really liked the bass and overall sound quality.",
  },
  {
    id: 4,
    productId: 1,
    name: "Neha Gupta",
    rating: 4,
    review: "Comfortable even after using them for a few hours.",
  },
  {
    id: 5,
    productId: 1,
    name: "Rohan Mehta",
    rating: 3,
    review: "Sound is good, but the build quality could be better.",
  },
  {
    id: 6,
    productId: 1,
    name: "Sneha Patel",
    rating: 5,
    review: "Battery easily lasts me the whole day. Very satisfied.",
  },
  {
    id: 7,
    productId: 1,
    name: "Arjun Kumar",
    rating: 4,
    review: "Bluetooth connects quickly and the range is pretty good.",
  },
  {
    id: 8,
    productId: 1,
    name: "Ananya Roy",
    rating: 5,
    review: "Great for music and online classes. Definitely worth buying.",
  },
  {
    id: 9,
    productId: 1,
    name: "Vikas Yadav",
    rating: 3,
    review: "Decent headphones, but the ear cushions get warm after long use.",
  },
  {
    id: 10,
    productId: 1,
    name: "Karan Malhotra",
    rating: 4,
    review: "Good sound, nice design and solid battery backup.",
  },
];
